version: "3.1"

services:

  joomla:
    image: joomla:php7.4-apache
    container_name: Joomla
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomlaDB
    volumes:
      - ./joomla:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: MySQL
    restart: always
    environment:
      MYSQL_DATABASE: joomlaDB
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql